// Leyenda de los íconos de trazo uniforme (fuente /public/fonts/iconos.woff2, Lucide, licencia ISC).
// En el código aparecen como un carácter invisible del rango privado (se ve como un cuadradito en el editor).
// Este archivo solo documenta cuál es cuál; no se importa desde ningún lado.
export const ICONOS_LEYENDA = {
  '\ue03a': 'alarm-clock',
  '\ue04c': 'arrow-left',
  '\ue05f': 'bell',
  '\ue069': 'calendar',
  '\ue06d': 'check',
  '\ue085': 'circle-x',
  '\ue087': 'clipboard-list',
  '\ue088': 'clock',
  '\ue0b3': 'download',
  '\ue0bb': 'eye',
  '\ue0bc': 'eye-off',
  '\ue0cd': 'file-text',
  '\ue0d4': 'flame',
  '\ue0f2': 'heart',
  '\ue0f6': 'image',
  '\ue10c': 'lock',
  '\ue117': 'message-circle',
  '\ue11f': 'moon',
  '\ue12e': 'paperclip',
  '\ue13f': 'plus',
  '\ue14f': 'save',
  '\ue153': 'search',
  '\ue174': 'square-pen',
  '\ue178': 'star',
  '\ue17a': 'sun',
  '\ue182': 'target',
  '\ue18c': 'trash-2',
  '\ue18e': 'trending-down',
  '\ue18f': 'trending-up',
  '\ue191': 'triangle-alert',
  '\ue1b0': 'x',
  '\ue1b2': 'zap',
  '\ue1c1': 'lightbulb',
  '\ue1f7': 'pencil',
  '\ue225': 'circle-check',
  '\ue258': 'pin',
  '\ue285': 'rocket',
  '\ue29a': 'clapperboard',
  '\ue2a1': 'bar-chart-3',
  '\ue346': 'party-popper',
  '\ue416': 'sparkles',
  '\ue4b2': 'presentation',
};
